<?php

namespace frontend\models\portal;

use frontend\components\behaviors\CommonModelBehavior;
use Yii;
use frontend\models\User;

/**
 * This is the model class for table "{{%portal_account}}".
 *
 * @property int $id
 * @property string|null $username Имя/адрес электронной почты
 * @property string|null $password Пароль
 * @property string|null $description Описание/дополнительная информация
 * @property int|null $portal_id Портал
 * @property string|null $date_added Дата добавления
 * @property int|null $status Статус аккаунта
 * @property int|null $added_by Добавил пользователь
 *
 * @property Portal $portal
 * @property User $addedBy
 */
class Account extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%portal_account}}';
    }

    /**
     * Подлючаем поведения.
     * @return array|void
     */
    public function behaviors()
    {
        $list = parent::behaviors(); // TODO: Change the autogenerated stub
        $list['common'] = [
            'class' => CommonModelBehavior::class,
        ];

        return $list;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['portal_id', 'status', 'added_by'], 'default', 'value' => null],
            [['portal_id', 'status', 'added_by'], 'integer'],
            [['date_added'], 'safe'],
            [['username'], 'string', 'max' => 128],
            [['password'], 'string', 'max' => 64],
            [['portal_id'], 'exist', 'skipOnError' => true, 'targetClass' => Portal::className(), 'targetAttribute' => ['portal_id' => 'id']],
            [['added_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['added_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'description' => 'Description',
            'portal_id' => 'Portal ID',
            'date_added' => 'Date Added',
            'status' => 'Status',
            'added_by' => 'Added By',
        ];
    }

    /**
     * Gets query for [[Portal]].
     *
     * @return \yii\db\ActiveQuery|PortalQuery
     */
    public function getPortal()
    {
        return $this->hasOne(Portal::className(), ['id' => 'portal_id']);
    }

    /**
     * Gets query for [[AddedBy]].
     *
     * @return \yii\db\ActiveQuery|UserQuery
     */
    public function getAddedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'added_by']);
    }

    /**
     * {@inheritdoc}
     * @return AccountQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AccountQuery(get_called_class());
    }
}
