<?php

namespace frontend\models\portal;

use frontend\components\behaviors\CommonModelBehavior;
use frontend\components\behaviors\ModelImageUploadBehavior;
use Imagine\Image\Box;
use Yii;
use frontend\models\User;
use frontend\models\portal\queries\PortalQuery;
use yii\helpers\FileHelper;
use yii\imagine\Image;
use yii\web\UploadedFile;

/**
 * This is the model class for table "portal".
 *
 * @property int $id
 * @property string|null $name Название портала
 * @property string|null $url Адрес портала
 * @property string|null $description Описание портала
 * @property int|null $status Статус портала
 * @property int|null $added_by Добавивший пользователь
 * @property string|null $date_added Дата добавления
 * @property string|null $logo_name Логотип портала
 *
 * @property User $addedBy
 * @property PortalAccount[] $portalAccounts
 */
class Portal extends \yii\db\ActiveRecord
{
    /**
     * Путь к общей папке с загрузкой
     */
//    public const UPLOAD_FOLDER_PATH = "uploads/portal/logo";
//    /**
//     * Путь к папке с оригинальнными загружаемыми картинками логотипов
//     */
//    private const UPLOAD_FOLDER_ORIGIN = "frontend/web/uploads/portals/logos/origins";
    /**
     * Путь к папке с жатыми картинками логотипов
     */
    public const UPLOAD_FOLDER = 'frontend/web/uploads/portals';

    public const FILES_WEB_FILE_PATH = '/uploads/portals';
    /**
     * Ширина превьюшки логотипа
     */
    public const LOGO_PREVIEW_WIDTH = 175;
    /**
     * Высота превьюшки логотипа
     */
    public const LOGO_PREVIEW_HEIGHT = 100;

    /**
     * @var UploadedFile
     */
    public $logoFile;
    /**
     * @var string путь
     */
    private $logoName;
    /**
     * @var
     */
    public $deleteLogo = 0;

    /**
     * Имя сценария создания
     */
    public const SCENARIO_CREATE = 'scenarioCreate';
    /**
     * Имя сценария редактирования
     */
    public const SCENARIO_UPDATE = 'scenarioUpdate';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%portal}}';
    }

    /**
     * Поведения
     * @return array
     */
    public function behaviors()
    {
        $list = parent::behaviors(); // TODO: Change the autogenerated stub
        $list['common'] = [
            'class' => CommonModelBehavior::class,
        ];
        $list['file'] = [
            'class' => ModelImageUploadBehavior::class,
//            'filePrefixLength' => '6',
//            'webPath' => static::FILES_WEB_FILE_PATH,
//            'folderPath' => static::UPLOAD_FOLDER,
//            'attributesSetting' => [
//                'logoFile' => [
//                    'dbAttribute' => 'logo_name',
//                    'width' => 125,
//                    'height' => 90,
//                    'subfolder' => '/previews/',
//                ],
//            ],
            'attributesSettings' => [
//                'logoFile' => [
//                    'dbAttribute' => 'logo_path', // колонка в базе, в которую нужно записать путь к файлу (будет записано имя файла)
//                    'folderSettings' => [ //
//                        'folderPath' => static::UPLOAD_FOLDER, // если нужно, чтобы изоюаржения данного аттрибута помещались
//                        // в отличную от глобальной директорию парметр subFolder будет проигнорирован
//                        'subFolder' => '/logos', // поддиректория в которую следует помещать изображения данного аттриубута
//                        'webPath' => static::FILES_WEB_FILE_PATH // необходимо для получения ссылки на файл, доступной из web
//                    ],
//                    'previewSettings' => [ // настройки превью изображения, если не указан, то превью не будет создано
//                        'folder' => '/previews', //директория в которую нужно помещать загруженные изображения
//                        'width' => 125, // ширина превью
//                        'height' => 75, // высота превью
//                    ],
//                    'deleteAttribute' => 'deleteLogo', // может быть использован, если например удаление
//                    'multiple' => false, // если с помощью данного аттрибута загружается несколько файлов то это немного
//                    // изменяет логику и в базу, если нужно, будет записан путь не для конкретного файла, а путь до папки
//                    // с файлами. TODO: пока что на будущее. пока что реализация не требуется.
//                ],
                    'logoFile' => [
                        'dbAttribute' => 'logo_name',
                        'webPath' => static::FILES_WEB_FILE_PATH,
                        'folderAlias' => static::UPLOAD_FOLDER,
                        'generateName' => true,
                        'generatedNameLength'=> 15,
                        'previewHeight' => 70,
                        'previewWidth' => 125,
                        'previewQuality' => 90,
                        // 'previewPrefix' => 'thumb_',
                        // 'previewPrefix' => '',
                        'previewSubFolder' => false,
                        // 'deleteAttribute',
                        // 'generatePreview',
                    ],



            ],
        ];
        return $list;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],

            [['status'], 'integer'],
            [['date_added', 'added_by'], 'safe'],
            [['status'], 'default', 'value' => 1],
            [['name', 'url'], 'string', 'max' => 256],
            [['logo_name'], 'string', 'max' => 512],
            [['added_by'],
                'exist',
                'skipOnError' => true,
                'targetClass' => User::className(),
                'targetAttribute' => ['added_by' => 'id']
            ],
            [
                ['logoFile'],
                'file',
                'skipOnEmpty' => true,
                'extensions' => 'png, jpg, bmp, gif, svg'
            ],
            [
                'deleteLogo',
                'in',
                'range' => [0, 1]
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название портала',
            'url' => 'Адрес портала',
            'description' => 'Описание портала',
            'status' => 'Статус портала',
            'added_by' => 'Добавивший пользователь',
            'date_added' => 'Дата добавления',
            'logo_name' => 'Логотип портала',
            'deleteLogo' => 'Удалить существующий логотип',
            'logoFile' => 'Загрузить логотип',
        ];
    }

    /**
     * Gets query for [[AddedBy]].
     *
     * @return \yii\db\ActiveQuery|UserQuery
     */
    public function getAddedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'added_by']);
    }

    /**
     * Gets query for [[PortalAccounts]].
     *
     * @return \yii\db\ActiveQuery|PortalAccountQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(Account::className(), ['portal_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return PortalQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PortalQuery(get_called_class());
    }

    /**
     * @param $extension
     * @throws \yii\base\Exception
     */
    private function generateFileName($extension)
    {
        $this->logoName = "logo_" . \yii::$app->security->generateRandomString(16) . ".$extension";
    }

//    /**
//     * @return bool
//     * @throws \yii\base\Exception
//     */
//    public function uploadLogo()
//    {
//        $logoFile = $this->logoFile;
//        if ($this->logoFile != null) {
//            $this->generateFileName($this->logoFile->extension);
//            $fullPath = yii::getAlias("@".static::UPLOAD_FOLDER_ORIGIN) . "/{$this->logoName}";
//            $filePath = "@".static::UPLOAD_FOLDER_ORIGIN . "/{$this->logoName}";
//            $isFileSaved = $this->logoFile->saveAs(
//                $filePath
//            );
//            if ($isFileSaved === true) {
//                $this->logo_name = $this->logoName;
//            }
//            $this->generateLogoPreview($fullPath);
//            return $isFileSaved;
//        }
//
//        return true;
//    }

    /**
     * @param $originPath
     */
    private function generateLogoPreview($originPath)
    {
        $previewPath = \yii::getAlias("@".static::UPLOAD_FOLDER_PREVIEW)."/{$this->logo_name}";

        $isMoved = copy($originPath, $previewPath);
        if ($isMoved === true) {
            $imagine = Image::getImagine();
            $thumb = $imagine->open($previewPath);
            $thumb->resize(
                new Box(static::LOGO_PREVIEW_WIDTH, static::LOGO_PREVIEW_HEIGHT)
            )
            ->save($previewPath, ['quality' => 85]);
        }
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getWebLogosPath()
    {
        return static::FILES_WEB_FILE_PATH . "/logos";
    }

    /**
     * @return string
     */
    public function getPreviewFilePath()
    {
        return $this->getWebLogosPath() . "/previews/{$this->logo_name}";
    }

    /**
     * @return bool
     */
    private function deleteLogo()
    {
        if ($this->deleteLogo == 1) {
            if ($this->logo_name !== null) {
                $this->softDeleteFile('logo_name');
            }
        }

        return true;
    }

    /**
     * @return array|array[]|\string[][]
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[static::SCENARIO_CREATE]
            = [
                'name',
                'url',
                'description',

                // 'status',
                // 'added_by',
                // 'date_added',
                // 'logo_name',
            ]
        ;

        $scenarios[static::SCENARIO_UPDATE] = [
            'name',
            'url',
            'description',
            'deleteLogo',
        ];


        return $scenarios;
    }

    /**
     * @return string
     */
    public function getLogoUrl()
    {

        return $this->logo_name === null
            ? null
            : static::FILES_WEB_FILE_PATH . "/previews/{$this->logo_name}";
    }

}
