<?php

namespace frontend\models\portal;

use frontend\components\behaviors\CommonModelBehavior;
use Yii;
use frontend\models\User;
use frontend\models\portal\queries\PortalQuery;

/**
 * This is the model class for table "portal".
 *
 * @property int $id
 * @property string|null $name Название портала
 * @property string|null $url Адрес портала
 * @property string|null $description Описание портала
 * @property int|null $status Статус портала
 * @property int|null $added_by Добавивший пользователь
 * @property string|null $date_added Дата добавления
 * @property string|null $logo_path Логотип портала
 *
 * @property User $addedBy
 * @property PortalAccount[] $portalAccounts
 */
class Portal extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%portal}}';
    }

    /**
     * @var
     */
    public $logoFile;

    /**
     * Поведения
     * @return array
     */
    public function behaviors()
    {
        $list = parent::behaviors(); // TODO: Change the autogenerated stub
        $list['common'] = [
            'class' => CommonModelBehavior::class,
        ];
        return $list;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['url', 'description'], 'string'],
            [['status', 'added_by'], 'default', 'value' => null],
            [['status', 'added_by'], 'integer'],
            [['date_added'], 'safe'],
            [['name'], 'string', 'max' => 256],
            [['logo_path'], 'string', 'max' => 512],
            [['added_by'],
                'exist',
                'skipOnError' => true,
                'targetClass' => User::className(),
                'targetAttribute' => ['added_by' => 'id']
            ],
            [
                ['logoFile'],
                'file',
                'skipOnEmpty' => false,
                'extensions' => 'png, jpg, bmp, gif',
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название портала',
            'url' => 'Адрес портала',
            'description' => 'Описание портала',
            'status' => 'Статус портала',
            'added_by' => 'Добавивший пользователь',
            'date_added' => 'Дата добавления',
            'logo_path' => 'Логотип портала',
        ];
    }

    /**
     * Gets query for [[AddedBy]].
     *
     * @return \yii\db\ActiveQuery|UserQuery
     */
    public function getAddedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'added_by']);
    }

    /**
     * Gets query for [[PortalAccounts]].
     *
     * @return \yii\db\ActiveQuery|PortalAccountQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(Account::className(), ['portal_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return PortalQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PortalQuery(get_called_class());
    }

    public function uploadLogo()
    {

    }

}
